### ISSUE TITLE
Spec test failing after updating to latest ubuntu

### ISSUE THREAD

**Issue by rgardner4012** [simp/simp-utils#49]
Need to update job to install createrepo_c instead of older createrepo

 /home/runner/work/simp-utils/simp-utils/scripts/bin/unpack_dvd:163:in `popen': No such file or directory - createrepo (Errno::ENOENT)
	from /home/runner/work/simp-utils/simp-utils/scripts/bin/unpack_dvd:163:in `block in update_yum_repo'
	from /home/runner/work/simp-utils/simp-utils/scripts/bin/unpack_dvd:128:in `chdir'
	from /home/runner/work/simp-utils/simp-utils/scripts/bin/unpack_dvd:128:in `update_yum_repo'
	from /home/runner/work/simp-utils/simp-utils/scripts/bin/unpack_dvd:353:in `unpack_and_create_yum_repo_from_iso'
	from /home/runner/work/simp-utils/simp-utils/scripts/bin/unpack_dvd:647:in `<main>'
        executes without failures (FAILED - 1)

**Comment by silug** [comment]
I "fixed" this in #58 by not running the tests if `createrepo` is not available.
